### ISSUE TITLE
Mod name confliction

### ISSUE THREAD

**Issue by Ludeo** [speecil/CustomMenuText#1]
The name of this mod might be confusing for some people, that have played bs version 1.19 and prior to this because there was a mod called CustomMenuText as well. That mod changed the text of the BeatSaber logo that you can see up in the sky. When anyone decides to update the mod again it would cause name complications and you won't be able to have both mods at the same time.

**Comment by speecil** [comment]
Ah, I see. I will change the name of the mod in the next iteration
